### ISSUE TITLE
Adminsidan

### ISSUE THREAD

**Issue by sweets86** [EssaBarbar/Webbshop#17]
"Styla" sidan som man kommer till när man loggar in som admin.
Fundera kring funktionerna som länkarna på sidan ska generera.

**Comment by baraabd** [comment]
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="./css/style.css">
    <title>Admin Panel</title>
</head>

<body>
    <div id="header">

    </div>

    <div id="bodyLeft">
        <h3>Content Management</h3>

        <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">Categories</a></li>
            <li><a href="#">Products</a></li>
            <li><a href="#">Users</a></li>
            <li><a href="#">Orders</a></li>
            <li><a href="#">Render requests</a></li>
            <li><a href="#">Manage admins</a></li>
        </ul>
    </div>

    <div id="bodyRight">

    </div>



</body>

</html>

--------------------------------------------------------------
CSS
--------------------------------------------------------------
* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
}

body {
    background-color: #4a4072;
}

#header {
    width: 98%;
    height: 50px;
    margin: 1%;
    background-color: #7271da;
    border-radius: 3px;
}

#bodyLeft {
    width: 24%;
    height: 500px;
    background-color: #4a4072;
    margin: 10px;
    border-radius: 3px;
    float: left;
}

#bodyLeft h3 {
    background-color: #4a4072;
    color: #fff;
    height: 40px;
    line-height: 40px;
    border-radius: 3px;
    text-align: center;
}

#bodyLeft ul {
    list-style-type: none;
    margin-top: 10px;
}

#bodyLeft ul li {
    height: 30px;
    line-height: 30px;
    border-radius: 3px;
}

#bodyLeft ul li a {
    text-decoration: none;
    color: #fff;
    padding-left: 3%;
    display: block;
}

#bodyLeft ul li:hover {
    background-color: #221c3b;
}

#bodyRight {
    width: 73%;
    height: 500px;
    background-color: #cccccc;
    margin: 10px;
    border-radius: 3px;
    float: left;
}
