### ISSUE TITLE
Tabeller/Kolumner Databas SQL

### ISSUE THREAD

**Issue by sweets86** [EssaBarbar/Webbshop#8]
Vi behöver lägga in tables och kolumner till vårt projekt: (produkt), (kategori), (fraktalternativ), (användare), (beställning) och (nyhetsbrev) till vår databas.
Innehåll:
Product: ProductID(12st), ProductName, CategoryId, UnitsInStock, UnitPrice, Description, Picture.
Varje kategori har 4 st produkter.
Category: CategoryID(3st), CategoryName(XBOX, PS4, PC).
Shipper: ShipperID, ShipperOptions(DHL, PostNord, Online).
User: UserID, Role, FirstName, LastName, Email, Password.
Order: OrderID, UserID, ShipperID, OrderDate, Recieved.
OrderDetails: OrderID, ProductID, Quantity, UnitPrice,
Newsletter: NewsletterID, FirstName, LastName,  Email, UserID.

**Comment by anukhatra** [comment]
Tillagt order_details(OrderID,ProductID)

[enjoy.zip](https://github.com/EssaBarbar/Webbshop/files/4161878/enjoy.zip)
